services:
  # nginx
  web:
    image: nginx:alpine
    ports:
      - "8000:80"
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf

  # php-fpm
  app:
    build:
      dockerfile: ./php/Dockerfile
    volumes:
      - ./app:/app
