services:
  # nginx
  web:
    image: nginx:alpine
    container_name: parser-app
    ports:
      - "8000:80"
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf

  # php-fpm
  app:
    container_name: parser-web
    image: php:8.2-fpm-alpine
    volumes:
      - ./app:/app
